language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a,x86
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository

before_script: cd xwords4/android/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-lxml imagemagick

script:
  - ./gradlew build assXw4Deb
